Mantenedor/Models/Categoria.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Categoria
    {
        public Categoria()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int IdCategoria { get; set; }
        public string NombreCategoria { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}

Mantenedor/Controllers/CategoriaController.cs
using Mantenedor.Models;
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Security;

namespace Mantenedor.Controllers
{
    public class CategoriaController : Controller
    {
        private MantenedorEntities db = new MantenedorEntities();

        public ActionResult Index()
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else if (Session["cargo"].ToString() == "1" || Session["cargo"].ToString() == "2")
            {
                return View(db.Categoria.ToList());
            }
            else
            {
                return RedirectToAction("../Home/Welcome");
            }
        }

        public ActionResult Create()
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else if (Session["cargo"].ToString() == "1" || Session["cargo"].ToString() == "2")
            {
                return View();
            }
            else
            {
                return RedirectToAction("../Home/Welcome");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCategoria,NombreCategoria")] Categoria categoria)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else if (Session["cargo"].ToString() == "1" || Session["cargo"].ToString() == "2")
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        db.Categoria.Add(categoria);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (Exception)
                    {
                        TempData["error"] = "Ya existe una categoría con este nombre";
                        return View();
                    }
                }
                return View(categoria);
            }
            else
            {
                return RedirectToAction("../Home/Welcome");
            }            
        }

        public ActionResult Edit(int? id)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else if (Session["cargo"].ToString() == "1" || Session["cargo"].ToString() == "2")
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Categoria categoria = db.Categoria.Find(id);
                if (categoria == null)
                {
                    return HttpNotFound();
                }
                return View(categoria);
            }
            else
            {
                return RedirectToAction("../Home/Welcome");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCategoria,NombreCategoria")] Categoria categoria)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else if (Session["cargo"].ToString() == "1" || Session["cargo"].ToString() == "2")
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        db.Entry(categoria).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (Exception)
                    {
                        TempData["error"] = "Ya existe una categoría con este nombre";
                        return View();
                    }
                    
                }
                return View(categoria);
            }
            else
            {
                return RedirectToAction("../Home/Welcome");
            }
        }

        public ActionResult Delete(int? id)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else if (Session["cargo"].ToString() == "1" || Session["cargo"].ToString() == "2")
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Categoria categoria = db.Categoria.Find(id);
                if (categoria == null)
                {
                    return HttpNotFound();
                }
                return View(categoria);
            }
            else
            {
                return RedirectToAction("../Home/Welcome");
            }
            
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else if (Session["cargo"].ToString() == "1" || Session["cargo"].ToString() == "2")
            {
                Categoria categoria = db.Categoria.Find(id);
                db.Categoria.Remove(categoria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("../Home/Welcome");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("../Home/Welcome");
        }

    }
}

Mantenedor/Views/Categoria/Create.cshtml
@model Mantenedor.Models.Categoria
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/_Layout.cshtml";
}

<h3>Agregar nueva categoría para los productos</h3>
<hr style="opacity: 0.2" />
<br />
@using (Html.BeginForm("Create", "Categoria", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    if (@ViewBag.Message != null)
    {
        <div class="center red">
            <h4 class="red-text">@ViewBag.Message</h4>
        </div>
    }
    if (TempData["error"] != null)
    {
        <div class="card-panel center">
            <h5 style="color: red;">@TempData["error"]</h5>
        </div>
    }
    <div class="input-field col s12">
        <label>Nombre de la categoría:</label>
        @Html.EditorFor(model => model.NombreCategoria)
    </div>
    <div class="input-field col s12">
        @Html.ValidationMessageFor(p => p.NombreCategoria, null, new { @style = "color: red" })
    </div>
    <div class="row">
        <button type="submit" class="waves-effect waves-light btn orange col s12">Agregar categoría</button>
    </div>
}
    <div class="row">
        <a class="btn btn-success col s12 orange" href="/Categoria/Index">Volver</a>
    </div>

Mantenedor/Views/Categoria/Edit.cshtml
@model Mantenedor.Models.Categoria
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">
    <h4 class="center">Cambio de nombre de categoría</h4>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()
        if (@ViewBag.Message != null)
        {
            <div class="center red">
                <h4 class="red-text">@ViewBag.Message</h4>
            </div>
        }
        if (TempData["error"] != null)
        {
            <div class="card-panel center">
                <h5 style="color: red;">@TempData["error"]</h5>
            </div>
        }
        <div class="row">
            <div class="input-field col s12">
                <label>Id de la categoría:</label>
                @Html.TextBoxFor(model => model.IdCategoria, new { @readonly = "readonly" })
            </div>
        </div>
        <div class="input-field col s12">
            <label>Nombre de la categoría:</label>
            @Html.EditorFor(model => model.NombreCategoria)
        </div>
        <div class="input-field col s12">
            @Html.ValidationMessageFor(p => p.NombreCategoria, null, new { @style = "color: red" })
        </div>
        <div class="row">
            <input class="btn btn-success col s12 orange" type="submit" value="Guardar cambios" />
        </div>
    }
    <div class="row">
        <a class="btn btn-success col s12 orange" href="/Categoria/Index">Volver</a>
    </div>
</div>

Mantenedor/Views/Categoria/Index.cshtml
@model IEnumerable<Mantenedor.Models.Categoria>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
}

<h3>Listado de categorias</h3>
<a class="btn btn-default waves-effect waves-light orange right" href="/Categoria/Create">Agregar nueva categoría</a>
<br />
<br />
<table id="listaCategorias" class="centered bordered striped">
    <thead>
        <tr>
            <th class="center">
                # <i class="material-icons">arrow_drop_down</i>
            </th>
            <th class="center">
                Nombre de la categoría <i class="material-icons">arrow_drop_down</i>
            </th>
            <th class="center">
                
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdCategoria)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreCategoria)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.IdCategoria })
                </td>
            </tr>
        }
    </tbody>
</table>