Mantenedor/Models/Usuario.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web.Mvc;

    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Nombre del trabajador invalido")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÑ]+$", ErrorMessage = "Ingrese solamente letras")]
        public string Nombre { get; set; }
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Apellido del trabajador invalido")]
        [RegularExpression(@"^[a-zA-Z\s ñáéíóúÑ]+$", ErrorMessage = "Ingrese solamente letras")]
        public string Apellido { get; set; }
        [Required(ErrorMessage = "Ingrese el correo electrónico", AllowEmptyStrings = false)]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Correo electrónico del trabajador invalido")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Correo electrónico invalido")]
        public string Correo { get; set; }
        [Required(ErrorMessage = "Ingrese una contraseña", AllowEmptyStrings = false)]
        [StringLength(30, MinimumLength = 6, ErrorMessage = "La contraseña debe tener como minimo 6 carácteres")]
        public string Contrasena { get; set; }
        [StringLength(11, MinimumLength = 11, ErrorMessage = "Formato valido: 569XXXXXXXX")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Ingrese solamente numeros")]
        public string Telefono { get; set; }
        [StringLength(70, MinimumLength = 6, ErrorMessage = "La direccion debe tener como mínimo 6 carácteres")]
        public string Direccion { get; set; }
        public int IdComuna { get; set; }
        public int IdCiudad { get; set; }
        public int IdSucursal { get; set; }
        public int IdCargo { get; set; }
        public int IdContrato { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual Comuna Comuna { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual Sucursal Sucursal { get; set; }

        public Usuario Existe(Usuario u)
        {
            Usuario user;
            using (var context = new MantenedorEntities())
            {
                user = context.Usuario.Where(uu => uu.Correo.Equals(u.Correo) && uu.Contrasena.Equals(u.Contrasena)).FirstOrDefault();
            }
            return user;
        }
    }
}

Mantenedor/Controllers/UsuarioController.cs
using Mantenedor.Models;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using System.Web.Security;

namespace Mantenedor.Controllers
{
    public class UsuarioController : Controller
    {
        private MantenedorEntities db = new MantenedorEntities();

        public ActionResult Index()
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else if(Session["cargo"].ToString() == "1" ||Session["cargo"].ToString() == "2")
            {
                var usuario = db.Usuario.Include(u => u.Cargo).Include(u => u.Ciudad).Include(u => u.Comuna).Include(u => u.Contrato).Include(u => u.Sucursal);
                return View(usuario.ToList());
            }else
            {
                return RedirectToAction("../Home/Welcome");
            }
        }

        public ActionResult Create()
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else if (Session["cargo"].ToString() == "1" || Session["cargo"].ToString() == "2")
            {
                ViewBag.IdCargo = new SelectList(db.Cargo, "IdCargo", "NombreCargo");
                ViewBag.IdCiudad = new SelectList(db.Ciudad, "IdCiudad", "NombreCiudad");
                ViewBag.IdComuna = new SelectList(db.Comuna, "IdComuna", "NombreComuna");
                ViewBag.IdContrato = new SelectList(db.Contrato, "IdContrato", "TipoContrato");
                ViewBag.IdSucursal = new SelectList(db.Sucursal, "IdSucursal", "NombreSucursal");
                return View();
            }else
            {
                return RedirectToAction("../Home/Welcome");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdUsuario,Nombre,Apellido,Correo,Contrasena,Telefono,Direccion,IdComuna,IdCiudad,IdSucursal,IdCargo,IdContrato")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    MailAddress m = new MailAddress(usuario.Correo);
                    db.Usuario.Add(usuario);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (System.Exception)
                {
                    ViewBag.IdCargo = new SelectList(db.Cargo, "IdCargo", "NombreCargo", usuario.IdCargo);
                    ViewBag.IdCiudad = new SelectList(db.Ciudad, "IdCiudad", "NombreCiudad", usuario.IdCiudad);
                    ViewBag.IdComuna = new SelectList(db.Comuna, "IdComuna", "NombreComuna", usuario.IdComuna);
                    ViewBag.IdContrato = new SelectList(db.Contrato, "IdContrato", "TipoContrato", usuario.IdContrato);
                    ViewBag.IdSucursal = new SelectList(db.Sucursal, "IdSucursal", "NombreSucursal", usuario.IdSucursal);
                    TempData["error"] = "Correo invalido o ya utilizado por un trabajador";
                    return View();
                }
            }
            ViewBag.IdCargo = new SelectList(db.Cargo, "IdCargo", "NombreCargo", usuario.IdCargo);
            ViewBag.IdCiudad = new SelectList(db.Ciudad, "IdCiudad", "NombreCiudad", usuario.IdCiudad);
            ViewBag.IdComuna = new SelectList(db.Comuna, "IdComuna", "NombreComuna", usuario.IdComuna);
            ViewBag.IdContrato = new SelectList(db.Contrato, "IdContrato", "TipoContrato", usuario.IdContrato);
            ViewBag.IdSucursal = new SelectList(db.Sucursal, "IdSucursal", "NombreSucursal", usuario.IdSucursal);
            return View(usuario);
        }

        public ActionResult Edit(int? id)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else if (Session["cargo"].ToString() == "1" || Session["cargo"].ToString() == "2")
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Usuario usuario = db.Usuario.Find(id);
                if (usuario == null)
                {
                    return HttpNotFound();
                }
                ViewBag.IdCargo = new SelectList(db.Cargo, "IdCargo", "NombreCargo", usuario.IdCargo);
                ViewBag.IdCiudad = new SelectList(db.Ciudad, "IdCiudad", "NombreCiudad", usuario.IdCiudad);
                ViewBag.IdComuna = new SelectList(db.Comuna, "IdComuna", "NombreComuna", usuario.IdComuna);
                ViewBag.IdContrato = new SelectList(db.Contrato, "IdContrato", "TipoContrato", usuario.IdContrato);
                ViewBag.IdSucursal = new SelectList(db.Sucursal, "IdSucursal", "NombreSucursal", usuario.IdSucursal);
                return View(usuario);
            }else
            {
                return RedirectToAction("../Home/Welcome");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdUsuario,Nombre,Apellido,Correo,Contrasena,Telefono,Direccion,IdComuna,IdCiudad,IdSucursal,IdCargo,IdContrato")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    MailAddress m = new MailAddress(usuario.Correo);
                    db.Entry(usuario).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (System.Exception)
                {
                    ViewBag.IdCargo = new SelectList(db.Cargo, "IdCargo", "NombreCargo", usuario.IdCargo);
                    ViewBag.IdCiudad = new SelectList(db.Ciudad, "IdCiudad", "NombreCiudad", usuario.IdCiudad);
                    ViewBag.IdComuna = new SelectList(db.Comuna, "IdComuna", "NombreComuna", usuario.IdComuna);
                    ViewBag.IdContrato = new SelectList(db.Contrato, "IdContrato", "TipoContrato", usuario.IdContrato);
                    ViewBag.IdSucursal = new SelectList(db.Sucursal, "IdSucursal", "NombreSucursal", usuario.IdSucursal);
                    TempData["error"] = "Correo invalido o ya utilizado por un trabajador";
                    return View();
                }
            }
            ViewBag.IdCargo = new SelectList(db.Cargo, "IdCargo", "NombreCargo", usuario.IdCargo);
            ViewBag.IdCiudad = new SelectList(db.Ciudad, "IdCiudad", "NombreCiudad", usuario.IdCiudad);
            ViewBag.IdComuna = new SelectList(db.Comuna, "IdComuna", "NombreComuna", usuario.IdComuna);
            ViewBag.IdContrato = new SelectList(db.Contrato, "IdContrato", "TipoContrato", usuario.IdContrato);
            ViewBag.IdSucursal = new SelectList(db.Sucursal, "IdSucursal", "NombreSucursal", usuario.IdSucursal);
            return View(usuario);
        }

        public ActionResult Delete(int? id)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else if (Session["cargo"].ToString() == "1" || Session["cargo"].ToString() == "2")
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Usuario usuario = db.Usuario.Find(id);
                if (usuario == null)
                {
                    return HttpNotFound();
                }
                return View(usuario);
            }else
            {
                return RedirectToAction("../Home/Welcome");
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Usuario usuario = db.Usuario.Find(id);
            db.Usuario.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Show(int? id)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else if (Session["cargo"].ToString() == "1" || Session["cargo"].ToString() == "2")
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Usuario usuario = db.Usuario.Find(id);
                if (usuario == null)
                {
                    return HttpNotFound();
                }
                return View(usuario);
            }else
            {
                return RedirectToAction("../Home/Welcome");
            }
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("../Home/Welcome");
        }

    }
}

Mantenedor/Views/Usuario/Create.cshtml
@model Mantenedor.Models.Usuario

@{
    ViewBag.Title = "Ingreso de usuarios";
    Layout = "~/Views/_Layout.cshtml";
}


<div class="row">
<h4>Formularío de creación de usuario</h4>
<hr style="opacity: 0.2" />
@using (Html.BeginForm("Create", "Usuario", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    if (@ViewBag.Message != null)
    {
        <div class="center red">
            <h4 class="red-text">@ViewBag.Message</h4>
        </div>
    }
    if (TempData["error"] != null)
    {
        <div class="card-panel center">
            <h5 style="color: red;">@TempData["error"]</h5>
        </div>
    }
    <br />
    <div class="col s12">
        <div class="row">
            <div class="input-field col s6">
                <label>Nombre:</label>
                @Html.TextBoxFor(u => u.Nombre, new {required = "required" })
            </div>
            <div class="input-field col s6">
                <label>Apellido:</label>
                @Html.TextBoxFor(u => u.Apellido, new {required = "required" })
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                @Html.ValidationMessageFor(u => u.Nombre, null, new { @style = "color: red" })
            </div>
            <div class="col s6">
                @Html.ValidationMessageFor(u => u.Apellido, null, new { @style = "color: red" })
            </div>
        </div>
        <hr style="opacity: 0.4" />
        <div class="row">
            <div class="input-field col s6">
                <label>Correo:</label>
                @Html.TextBoxFor(u => u.Correo, new {required = "required" })
            </div>
            <div class="input-field col s6">
                <label>Contraseña:</label>
                @Html.PasswordFor(u => u.Contrasena, new {required = "required"})
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                @Html.ValidationMessageFor(u => u.Correo, null, new { @style = "color: red" })
            </div>
            <div class="col s6">
                @Html.ValidationMessageFor(u => u.Contrasena, null, new { @style = "color: red" })
            </div>
        </div>
        <hr style="opacity: 0.4" />
        <div class="row">
            <div class="input-field col s6">
                <label>Teléfono:</label>
                @Html.TextBoxFor(u => u.Telefono, new {required = "required" })
            </div>
            <div class="input-field col s6">
                <label>Dirección donde reside:</label>
                @Html.TextBoxFor(u => u.Direccion, new {required = "required" })
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                @Html.ValidationMessageFor(u => u.Telefono, null, new { @style = "color: red" })
            </div>
            <div class="col s6">
                @Html.ValidationMessageFor(u => u.Direccion, null, new { @style = "color: red" })
            </div>
        </div>
        <hr style="opacity: 0.4" />
        <div class="row">
            <div class="input-field col s6">
                @Html.DropDownList("IdCiudad", null, htmlAttributes: new { @class = "form-control" })
                <label>Ciudad donde reside:</label>
            </div>
            <div class="input-field col s6">
                @Html.DropDownList("IdComuna", null, htmlAttributes: new { @class = "form-control" })
                <label>Comuna donde reside:</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                @Html.DropDownList("IdSucursal", null, htmlAttributes: new { @class = "form-control" })
                <label>Sucursal:</label>
            </div>
            <div class="input-field col s6">
                @Html.DropDownList("IdCargo", null, htmlAttributes: new { @class = "form-control" })
                <label>Cargo:</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                @Html.DropDownList("IdContrato", null, htmlAttributes: new { @class = "form-control" })
                <label>Tipo de contrato:</label>
            </div>
        </div>
        <div class="row">
            <button type="submit" class="waves-effect waves-light btn orange col s12">Crear trabajador</button>
        </div>
        <div class="row">
            <a class="btn btn-success col s12 orange" href="/Usuario/Index">Volver</a>
        </div> 
    </div>
}   
    
</div>

Mantenedor/Views/Usuario/Delete.cshtml
@model Mantenedor.Models.Usuario
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="center">
    <h3>Eliminar cuenta de trabajador @Html.DisplayFor(model => model.Nombre) @Html.DisplayFor(model => model.Apellido)</h3>
    <h5>¿Seguro que desea eliminar la cuenta de este trabajador?</h5>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <br />
            <input type="submit" value="Eliminar" class="btn btn-default red" /> 
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default blue" })
        </div>
    }
</div>

Mantenedor/Views/Usuario/Edit.cshtml
@model Mantenedor.Models.Usuario

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">
    <h4 class="center">Formularío de modificación de usuario</h4>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()
        if (@ViewBag.Message != null)
        {
            <div class="center red">
                <h4 class="red-text">@ViewBag.Message</h4>
            </div>
        }
        if (TempData["error"] != null)
        {
            <div class="card-panel center">
                <h5 style="color: red;">@TempData["error"]</h5>
            </div>
        }
        <div class="row">
            <div class="input-field col s12">
                <label>Id del trabajador:</label>
                @Html.TextBoxFor(model => model.IdUsuario, new { @readonly = "readonly" })
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <label>Nombre del trabajador:</label>
                @Html.EditorFor(model => model.Nombre)
            </div>
            <div class="input-field col s6">
                <label>Apellido del trabajador:</label>
                @Html.EditorFor(model => model.Apellido)
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                @Html.ValidationMessageFor(u => u.Nombre, null, new { @style = "color: red" })
            </div>
            <div class="col s6">
                @Html.ValidationMessageFor(u => u.Apellido, null, new { @style = "color: red" })
            </div>
        </div>
        <hr style="opacity: 0.2" />
        <div class="row">
            <div class="input-field col s6">
                <label>Correo del trabajador:</label>
                @Html.EditorFor(model => model.Correo)
            </div>
            <div class="input-field col s6">
                <label>Contraseña del trabajador:</label>
                @Html.PasswordFor(model => model.Contrasena)
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                @Html.ValidationMessageFor(u => u.Correo, null, new { @style = "color: red" })
            </div>
            <div class="col s6">
                @Html.ValidationMessageFor(u => u.Contrasena, null, new { @style = "color: red" })
            </div>
        </div>
        <hr style="opacity: 0.2" />
        <div class="row">
            <div class="input-field col s6">
                <label>Teléfono del trabajador:</label>
                @Html.EditorFor(model => model.Telefono)
            </div>
            <div class="input-field col s6">
                <label>Dirección del trabajador:</label>
                @Html.EditorFor(model => model.Direccion)
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                @Html.ValidationMessageFor(u => u.Telefono, null, new { @style = "color: red" })
            </div>
            <div class="col s6">
                @Html.ValidationMessageFor(u => u.Direccion, null, new { @style = "color: red" })
            </div>
        </div>
        <hr style="opacity: 0.2" />
        <div class="row">
            <div class="input-field col s6">
                @Html.DropDownList("IdCiudad", null, htmlAttributes: new { @class = "form-control" })
                <label>Ciudad donde reside el trabajador:</label>    
            </div>
            <div class="input-field col s6">
                @Html.DropDownList("IdComuna", null, htmlAttributes: new { @class = "form-control" })
                <label>Comuna donde reside el trabajador:</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                @Html.DropDownList("IdSucursal", null, htmlAttributes: new { @class = "form-control" })
                <label>Sucursal donde trabaja el trabajador:</label>
            </div>
        <div class="input-field col s6">
                @Html.DropDownList("IdCargo", null, htmlAttributes: new { @class = "form-control" })
                <label>Cargo del trabajador:</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                @Html.DropDownList("IdContrato", null, htmlAttributes: new { @class = "form-control" })
                <label>Tipo de contrato:</label>
            </div>
        </div>
        <div class="row">
            <input class="btn btn-success col s12 orange" type="submit" value="Guardar cambios" />
        </div>
}
        <div class="row">
            <a class="btn btn-success col s12 orange" href="/Usuario/Index">Volver</a>
        </div>     
</div>

Mantenedor/Views/Usuario/Index.cshtml
@model IEnumerable<Mantenedor.Models.Usuario>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
}

<h3>Listado de empleados</h3>
<a class="btn btn-default waves-effect waves-light orange right" href="/Usuario/Create">Agregar nuevo trabajador</a>
<br />
<br />
<table id="listaEmpleados" class="centered bordered striped">
    <thead>
        <tr>
            <th class="center">
                Nombre <i class="material-icons">arrow_drop_down</i>
            </th>
            <th class="center">
                Apellido <i class="material-icons">arrow_drop_down</i>
            </th>
            <th class="center">
                Cargo <i class="material-icons">arrow_drop_down</i>
            </th>
            <th class="center">
                Contrato <i class="material-icons">arrow_drop_down</i>
            </th>
            <th class="center">
                Sucursal <i class="material-icons">arrow_drop_down</i>
            </th>
            <th class="center">
                
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cargo.NombreCargo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contrato.TipoContrato)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sucursal.NombreSucursal)
                </td>
                <td>
                    @Html.ActionLink("Ver", "Show", new { id = item.IdUsuario }) | @Html.ActionLink("Editar", "Edit", new { id = item.IdUsuario }) | @Html.ActionLink("Eliminar", "Delete", new { id = item.IdUsuario })
                </td>
            </tr>
        }
        </tbody>
</table>

Mantenedor/Views/Usuario/Show.cshtml
@model Mantenedor.Models.Usuario
@{
    ViewBag.Title = "Show";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>Datos del empleado con ID @Html.DisplayFor(model => model.IdUsuario)</h2>

<div>
    <h4>Datos:</h4>
    <hr />
    <table class="centered bordered striped">
        <tr>
            <th class="center">
                Nombre
            </th>
            <th class="center">
                Apellido
            </th>
            <th class="center">
                Correo
            </th>
            <th class="center">
                Teléfono
            </th>
            <th class="center">
                Dirección
            </th>
            <th class="center">
                Cargo
            </th>
            <th class="center">
                Comuna
            </th>
            <th class="center">
                Ciudad
            </th>
            <th class="center">
                Contrato
            </th>
            <th class="center">
                Sucursal
            </th>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Nombre)
            </td>
            <td>
                @Html.DisplayFor(model => model.Apellido)
            </td>
            <td>
                @Html.DisplayFor(model => model.Correo)
            </td>
            <td>
                @Html.DisplayFor(model => model.Telefono)
            </td>
            <td>
                @Html.DisplayFor(model => model.Direccion)
            </td>
            <td>
                @Html.DisplayFor(model => model.Cargo.NombreCargo)
            </td>
            <td>
                @if (Model.Comuna.IdComuna == 0)
                {
                    @Html.Label("-")
                }else{
                    @Html.DisplayFor(model => model.Comuna.NombreComuna)
                }
            </td>
            <td>
                @Html.DisplayFor(model => model.Ciudad.NombreCiudad)
            </td>
            <td>
                @Html.DisplayFor(model => model.Contrato.TipoContrato)
            </td>
            <td>
                @Html.DisplayFor(model => model.Sucursal.NombreSucursal)
            </td>
        </tr>
    </table>
    <br />
    <span class="flow-text">
        @Html.ActionLink("Editar", "Edit", new { id = Model.IdUsuario }) |
        @Html.ActionLink("Volver", "Index", new { @class = "btn-success" })
    </span>
</div>