Mantenedor/Models/Producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        public int IdProducto { get; set; }
        [Required(ErrorMessage = "Campo obligatorio", AllowEmptyStrings = false)]
        public string NombreProducto { get; set; }
        [Required(ErrorMessage = "Campo obligatorio", AllowEmptyStrings = false)]
        [Positivo(ErrorMessage = "El stock disponible debe ser positivo")]
        public int StockDisponible { get; set; }
        [Required(ErrorMessage = "Campo obligatorio", AllowEmptyStrings = false)]
        [Positivo(ErrorMessage = "El stock total debe ser positivo")]
        public int StockTotal { get; set; }
        [Required(ErrorMessage = "Campo obligatorio", AllowEmptyStrings = false)]
        [Positivo(ErrorMessage = "El precio del producto debe ser positivo")]
        public int Precio { get; set; }
        public int IdCategoria { get; set; }
        public int IdSucursal { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
    
    public class Positivo : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            if (value == null)
            {
                return true;
            }
            int getal;
            if (int.TryParse(value.ToString(), out getal))
            {
                if (getal >= 0)
                    return true;
            }
            return false;
        }
    }
}

Mantenedor/Controllers/ProductoController.cs
using Mantenedor.Models;
using Mantenedor.Servicio;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Security;
using System.Net.Http;
using System.Collections.Generic;
using System.Web;
using System;
using System.Net.Http.Headers;

namespace Mantenedor.Controllers
{
    public class ProductoController : Controller
    {
        private MantenedorEntities db = new MantenedorEntities();

        public ActionResult Index()
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }else
            {
                List<Producto> lst = new List<Producto>();
                HttpClient client = new HttpClient();
                client.BaseAddress = new Uri("http://localhost:49353/");

                client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("aplication/json"));


                HttpResponseMessage response = client.GetAsync("api/Producto").Result;

                if (response.IsSuccessStatusCode)
                {
                    lst = response.Content.ReadAsAsync<List<Producto>>().Result;
                }

                return View(lst);

                //var producto = db.Producto.Include(u => u.Categoria).Include(u => u.Sucursal);
                //return View(producto.ToList());
            }
            
        }
        
        public ActionResult Create()
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else
            {
                ViewBag.IdCategoria = new SelectList(db.Categoria, "IdCategoria", "NombreCategoria");
                ViewBag.IdSucursal = new SelectList(db.Sucursal, "IdSucursal", "NombreSucursal");
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdProducto,NombreProducto,StockTotal,StockDisponible,Precio,IdCategoria,IdSucursal")] Producto producto)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    if (producto.StockTotal >= producto.StockDisponible)
                    {
                        db.Producto.Add(producto);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.IdCategoria = new SelectList(db.Categoria, "IdCategoria", "NombreCategoria");
                        ViewBag.IdSucursal = new SelectList(db.Sucursal, "IdSucursal", "NombreSucursal");
                        TempData["error"] = "El stock total no puede ser mayor al stock disponible";
                        return View();
                    }
                }
                ViewBag.IdCategoria = new SelectList(db.Categoria, "IdCategoria", "NombreCategoria", producto.IdCategoria);
                ViewBag.IdSucursal = new SelectList(db.Sucursal, "IdSucursal", "NombreSucursal", producto.IdSucursal);
                return View(producto);
            }
        }
        
        public ActionResult Edit(int? id)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Producto producto = db.Producto.Find(id);
                if (producto == null)
                {
                    return HttpNotFound();
                }
                ViewBag.IdCategoria = new SelectList(db.Categoria, "IdCategoria", "NombreCategoria", producto.IdCategoria);
                ViewBag.IdSucursal = new SelectList(db.Sucursal, "IdSucursal", "NombreSucursal", producto.IdSucursal);
                return View(producto);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdProducto,NombreProducto,StockTotal,StockDisponible,Precio,IdCategoria,IdSucursal")] Producto producto)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    if (producto.StockTotal >= producto.StockDisponible)
                    {
                        db.Entry(producto).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.IdCategoria = new SelectList(db.Categoria, "IdCategoria", "NombreCategoria");
                        ViewBag.IdSucursal = new SelectList(db.Sucursal, "IdSucursal", "NombreSucursal");
                        TempData["error"] = "El stock total no puede ser mayor al stock disponible";
                        return View();
                    }
                }
                ViewBag.IdCategoria = new SelectList(db.Categoria, "IdCategoria", "NombreCategoria", producto.IdCategoria);
                ViewBag.IdSucursal = new SelectList(db.Sucursal, "IdSucursal", "NombreSucursal", producto.IdSucursal);
                return View(producto);
            }
        }
        
        public ActionResult Delete(int? id)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Producto producto = db.Producto.Find(id);
                if (producto == null)
                {
                    return HttpNotFound();
                }
                return View(producto);
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["correo"] == null)
            {
                return RedirectToAction("../Home/Welcome");
            }
            else
            {
                Producto producto = db.Producto.Find(id);
                db.Producto.Remove(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Show(int? id)
        {
            if (Session["correo"] == null)
            {

                return RedirectToAction("../Home/Welcome");

            } else {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Producto producto= db.Producto.Find(id);
                if (producto == null)
                {
                    return HttpNotFound();
                }

                return View(producto);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Logout()
        {
           FormsAuthentication.SignOut();
           Session.Abandon();
           return RedirectToAction("../Home/Welcome");
        }
    }
}

Mantenedor/Views/Producto/Create.cshtml
@model Mantenedor.Models.Producto
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">
    <h4>Formularío de creación de producto</h4>
    <hr />
    @using (Html.BeginForm("Create", "Producto", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        if (@ViewBag.Message != null)
        {
            <div class="center red">
                <h4 class="red-text">@ViewBag.Message</h4>
            </div>
        }
        if (TempData["error"] != null)
        {
            <div class="card-panel center">
                <h5 style="color: red;">@TempData["error"]</h5>
            </div>
        }
        <div class="col s12">
            <div class="row">
                <div class="input-field col s6">
                    <label>Nombre del producto:</label>
                    @Html.TextBoxFor(p => p.NombreProducto, new { required = "required" })
                </div>
                <div class="input-field col s6">
                    <label>Stock total:</label>
                    @Html.TextBoxFor(p => p.StockTotal, new { required = "required" })
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    @Html.ValidationMessageFor(u => u.NombreProducto, null, new { @style = "color: red" })
                </div>
                <div class="col s6">
                    @Html.ValidationMessageFor(u => u.StockTotal, null, new { @style = "color: red" })
                </div>
            </div>
            <hr style="opacity: 0.2;" />
            <div class="row">
                <div class="input-field col s6">
                    <label>Stock disponible:</label>
                    @Html.TextBoxFor(p => p.StockDisponible, new { required = "required" })
                </div>
                <div class="input-field col s6">
                    <label>Precio:</label>
                    @Html.TextBoxFor(p => p.Precio, new { required = "required" })
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    @Html.ValidationMessageFor(u => u.StockDisponible, null, new { @style = "color: red" })
                </div>
                <div class="col s6">
                    @Html.ValidationMessageFor(u => u.Precio, null, new { @style = "color: red" })
                </div>
            </div>
            <hr style="opacity: 0.2;" />
            <div class="row">
                <div class="input-field col s6">
                    @Html.DropDownList("IdCategoria", null, htmlAttributes: new { @class = "form-control" })
                    <label>Categoría:</label>
                </div>
                <div class="input-field col s6">
                    @Html.DropDownList("IdSucursal", null, htmlAttributes: new { @class = "form-control" })
                    <label>Sucursal:</label>
                </div>
            </div>
            <div class="row">
                <button type="submit" class="waves-effect waves-light btn orange col s12">Agregar producto</button>
            </div>
        </div>
    }
</div>

Mantenedor/Views/Producto/Delete.cshtml
@model Mantenedor.Models.Producto
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="center">
    <h3>Eliminar producto con ID @Html.DisplayFor(model => model.IdProducto)</h3>
    <h5>¿Seguro que desea eliminar este producto de la base de datos?</h5>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <br />
            <input type="submit" value="Eliminar" class="btn btn-default red" />
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default blue" })
        </div>
    }
</div>

Mantenedor/Views/Producto/Edit.cshtml
@model Mantenedor.Models.Producto
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/_Layout.cshtml";
}

<div class="row">
    <h4>Modificación de producto con ID @Html.DisplayFor(model => model.IdProducto)</h4>
    <hr />
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()
        if (@ViewBag.Message != null)
        {
            <div class="center red">
                <h4 class="red-text">@ViewBag.Message</h4>
            </div>
        }
        if (TempData["error"] != null)
        {
            <div class="card-panel center">
                <h5 style="color: red;">@TempData["error"]</h5>
            </div>
        }
        <div class="col s12">
            <div class="row">
                <div class="input-field col s12">
                    <label>Id del producto:</label>
                    @Html.TextBoxFor(model => model.IdProducto, new { @readonly = "readonly" })
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <label>Nombre del producto:</label>
                    @Html.EditorFor(p => p.NombreProducto, new { required = "required" })
                </div>
                <div class="input-field col s6">
                    <label>Stock total:</label>
                    @Html.EditorFor(p => p.StockTotal, new { required = "required" })
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    @Html.ValidationMessageFor(u => u.NombreProducto, null, new { @style = "color: red" })
                </div>
                <div class="col s6">
                    @Html.ValidationMessageFor(u => u.StockTotal, null, new { @style = "color: red" })
                </div>
            </div>
            <hr style="opacity: 0.2;" />
            <div class="row">
                <div class="input-field col s6">
                    <label>Stock disponible:</label>
                    @Html.EditorFor(p => p.StockDisponible, new { required = "required" })
                </div>
                <div class="input-field col s6">
                    <label>Precio:</label>
                    @Html.EditorFor(p => p.Precio, new { required = "required" })
                </div>
            </div>
            <div class="row">
                <div class="col s6">
                    @Html.ValidationMessageFor(u => u.StockDisponible, null, new { @style = "color: red" })
                </div>
                <div class="col s6">
                    @Html.ValidationMessageFor(u => u.Precio, null, new { @style = "color: red" })
                </div>
            </div>
            <hr style="opacity: 0.2;" />
            <div class="row">
                <div class="input-field col s6">
                    @Html.DropDownList("IdCategoria", null, htmlAttributes: new { @class = "form-control" })
                    <label>Categoría:</label>
                </div>
                <div class="input-field col s6">
                    @Html.DropDownList("IdSucursal", null, htmlAttributes: new { @class = "form-control" })
                    <label>Sucursal:</label>
                </div>
            </div>
            <div class="row">
                <input class="btn btn-success col s12 orange" type="submit" value="Modificar producto" />
            </div>
        </div>
    }
</div>

Mantenedor/Views/Producto/Index.cshtml
@model IEnumerable<Mantenedor.Models.Producto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_Layout.cshtml";
}

<h3>Listado de productos</h3>
<a class="btn btn-default waves-effect waves-light orange right" href="/Producto/Create">Agregar nuevo producto</a>
<br />
<br />
<div id="tabla"></div>
<table id="listaProductos" class="centered bordered striped">
    <thead>
        <tr>
            <th class="center">
                # <i class="material-icons">arrow_drop_down</i>
            </th>
            <th class="center">
                Nombre del producto <i class="material-icons">arrow_drop_down</i>
            </th>
            <th class="center">
                Stock Disponible (%)<i class="material-icons">arrow_drop_down</i>
            </th>
            <th class="center">
                Precio <i class="material-icons">arrow_drop_down</i>
            </th>
            <th class="center">
                Bodega donde se encuentra <i class="material-icons">arrow_drop_down</i>
            </th>
            <th class="center">
                
            </th>
        </tr>
    </thead>
     <tbody>
   
    @foreach (var item in Model)
    {
            <tr>
               <td>
                    @Html.DisplayFor(modelItem => item.IdProducto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreProducto)
                </td>
                @if ((item.StockDisponible * 100) / item.StockTotal <= 25)
                 {
                    int x = (item.StockDisponible * 100) / item.StockTotal;
                    x.ToString();
                    <td><span style="color: red;">@x %</span></td>
                }
                else
                {
                    int x = (item.StockDisponible * 100) / item.StockTotal;
                    x.ToString();
                    <td>@x %</td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sucursal.NombreSucursal)
                </td>
                <td>
                    @Html.ActionLink("Ver", "Show", new { id = item.IdProducto }) | @Html.ActionLink("Editar", "Edit", new { id = item.IdProducto }) | @Html.ActionLink("Eliminar", "Delete", new { id = item.IdProducto })
                </td>
            </tr>
    }
         </tbody>
</table>
<br />
<span style="color:red;">* Si el % disponible esta en rojo, avisar a su supervisor</span>
<script>
    var uri = 'api/Producto';
    var rows = new Array();
    var producto;
    $(document).ready(function () {
        getAllItems()
        //});
        //function find() {
        //    var id = $('#clienteId').val();
        //    $.getJSON(uri + '/' + id)
        //    .done(function (data) {
        //        $('#editNombre').val(data.Nombre);
        //    }).fail(function (jqXHR, textStatus, err) {
        //        $('#cliente').text("error no se encuentra la persona");
        //    })
        //}
        function getAllItems() {
            var i = 0;
            $.getJSON(uri)
                .done(function (data) {
                    $.each(data, function (key, item) {
                        rows[i] = "row_" + item.IdProducto;
                        $('<tr id="' + rows[i] + '">' +
                                '<td>' + item.IdProducto + '</td>' +
                                '<td>' + item.NombreProducto + '</td>' +
                                '<td>' + item.ISucursal + '</td>'
                                + '<td> <button id="edit_' + item.IdProducto + '" onclick="javascript:editItem(' + item.IdProducto + ')">Editar</button> <button id="delete_' + item.IdProducto + '" onclick="javascript:deleteItem(' + item.IdProducto + ')">Eliminar</button></td>' +
                            '</tr>').appendTo($('#listaProductos>tbody'));
                        i++;
                    });
                });
        }
        function guardarAddButton() {
            cliente = new Object();
            cliente.Nombre = $('#addNombres').val();
            var clienteJSON = JSON.stringify(cliente);
            alert('aca');
            $.ajax({
                url: uri,
                type: 'POST',
                data: clienteJSON,
                contentType: "application/json;charset=utf-8",
                //}).
                //    done(function (response) {
                //        deleteAllItems();
                //        getAllItems();
                //    });
                success: function (response) {
                    deleteAllItems();
                    getAllItems();
                },
                error: function () {
                    alert('Ha ocurrido un error, por favor re intente.');
                }
            });
        }
        function deleteAllItems() {
            rows.forEach(function (item) {
                $('#' + item).remove();
            });
        }
        function guardarEditButton() {
            cliente.Nombre = $('#editNombre').val();
            var clienteJSON = JSON.stringify(cliente);
            $.ajax({
                url: uri + '/' + cliente.Id,
                type: 'PUT',
                data: clienteJSON,
                contentType: "application/json;charset=utf-8"
            }).
                done(function (response) {
                    deleteAllItems();
                    getAllItems();
                }).
                fail(function (jqXHR, textStatus, err) {
                    $('#cliente').text('Error, no se encuentra la persona');
                });
        }
        /*
            Se ocupa de las cabeceras de petición HTTP (tipos Modified-pasado, etag, Content-Type, MIME etc ...).
            Se ocupa de las devoluciones de llamada de la solicitud (incluyendo devoluciones de llamada promesa .done (), .fail () etc ...)
            Maneja cualquier prefiltros para la orden.
            Maneja cualquier tiempos de espera establecidos para la solicitud.
            Maneja todas las llamadas entre dominios (incluyendo jsonp).
        */
        function editItem(id) {
            $.getJSON(uri + '/' + id)
                .done(function (data) {
                    cliente = data;
                    $('#editNombre').val(data.Nombre);
                    $('#editNombre').attr('readonly', false);

                })
                .fail(function (jqXHR, textStatus, err) {
                    $('#cliente').text('Error, no se encuentra la persona');
                });

        }
        function deleteItem(id) {
            $.ajax({
                url: uri + '/' + id,
                type: 'DELETE',
                contentType: 'application/json;charset=utf-8',
                success: function (response) {
                    deleteAllItems();
                    getAllItems();
                },
                error: function (response) {
                    alert('Ha ocurrido un error, por favor re intente.');
                }
            });
        }
    });
</script>

Mantenedor/Views/Producto/Show.cshtml
@model Mantenedor.Models.Producto
@{
    ViewBag.Title = "Show";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>Datos del producto con ID @Html.DisplayFor(model => model.IdProducto)</h2>

<div>
    <h4>Datos:</h4>
    <hr />
    <table class="centered bordered striped">
        <tr>
            <th class="center">
                ID
            </th>
            <th class="center">
                Nombre del producto
            </th>
            <th class="center">
                Stock Total
            </th>
            <th class="center">
                Stock Disponible
            </th>
            <th class="center">
                Precio
            </th>
            <th class="center">
                Categoría
            </th>
            <th class="center">
                Bodega donde se encuentra
            </th>
        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.IdProducto)
            </td>
            <td>
                @Html.DisplayFor(model => model.NombreProducto)
            </td>
            <td>
                @Html.DisplayFor(model => model.StockTotal)
            </td>
            <td>
                @Html.DisplayFor(model => model.StockDisponible)
            </td>
            <td>
                @Html.DisplayFor(model => model.Precio)
            </td>
            <td>
                @Html.DisplayFor(model => model.Categoria.NombreCategoria)
            </td>
            <td>
                @Html.DisplayFor(model => model.Sucursal.NombreSucursal)
            </td>
        </tr>
    </table>
    <br />
    <span class="flow-text">
        @Html.ActionLink("Editar", "Edit", new { id = Model.IdProducto }) |
        @Html.ActionLink("Volver", "Index", new { @class = "btn-success" })
    </span>
</div>